
const uint OBJECT_COUNT = 65536;
const uint WORLD_SIZE = 500;
const uint CHUNK_COUNT_SIDE = 10;
const uint CHUNK_COUNT = CHUNK_COUNT_SIDE * CHUNK_COUNT_SIDE * CHUNK_COUNT_SIDE;
const uint MAX_OBJECTS_PER_CHUNK = OBJECT_COUNT * 4 / CHUNK_COUNT + 1;
const uint SORT_THREAD_COUNT = 64;
const uint SORT_OBJECT_COUNT = (OBJECT_COUNT + SORT_THREAD_COUNT - 1) / SORT_THREAD_COUNT;
const uint SORT_THREAD_OBJECT_PER_CHUNK = MAX_OBJECTS_PER_CHUNK / 4 + 1;
const uint OBJECT_UPDATE_COUNT = (OBJECT_COUNT + CHUNK_COUNT - 1) / CHUNK_COUNT;

const float BOID_DIST_MAX = 45.0f;
const float BOID_DIST_MIN = 10.0f;
const float BOID_MAX_SPEED = 300.0f;
